# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard 'mozrepl' do
  watch(/.+\.html/)
  watch(/assets\/(.+\.(css|js|html))/) { |m| m[1] }
end

### or with options...
# guard 'mozrepl', :host => 'localhost', :port => 4242, :verbose => true do
#   ...
